# Generated by Django 4.1 on 2022-08-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0002_estoqueproduto_data_lancamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estoqueproduto",
            name="data_lancamento",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
