# Generated by Django 4.1 on 2022-08-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0004_estoqueproduto_quantidade_delete_estoqueprodutoloja"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="custo",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="ean",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="referencia",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="usa_serial",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutocategoria",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutocategoria",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutosubcategoria",
            name="data_atualizacao",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutosubcategoria",
            name="data_cadastro",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="cupom",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="pagamento",
        ),
        migrations.RemoveField(
            model_name="pedidoitem",
            name="custo",
        ),
        migrations.RemoveField(
            model_name="pedidoitem",
            name="pontos",
        ),
        migrations.DeleteModel(
            name="PedidoCupom",
        ),
        migrations.DeleteModel(
            name="PedidoPagamento",
        ),
    ]
