# Generated by Django 4.1 on 2022-08-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0006_alter_estoqueproduto_imagens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedidoitem",
            name="produto",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="estoqueproduto",
            name="quantidade",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutocategoria",
            name="ativo",
        ),
        migrations.RemoveField(
            model_name="estoqueprodutosubcategoria",
            name="ativo",
        ),
        migrations.AlterField(
            model_name="estoqueproduto",
            name="informacoes",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
        migrations.DeleteModel(
            name="PedidoItem",
        ),
    ]
