# Generated by Django 4.1 on 2022-08-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("principal", "0007_remove_pedidoitem_produto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoqueproduto",
            name="mostrar_inicio",
            field=models.BooleanField(default=True),
        ),
    ]
